[package]
name = "text_changer"
authors = ["AveN RU"]
version = "0.1.1"
description = "Заменитель слов по словарю"
edition = "2024"

[dependencies]
indicatif = "0.18.2"
lazy_static = "1.5.0"
regex = "1.12.2"
calamine = "0.31.0"
rust_xlsxwriter = "0.90.2"
encoding_rs = "0.8.35"
encoding_rs_io = "0.1.7"
rtf-parser = "0.4.2"
zip = "6.0.0"
foldhash = "0.2.0"
#доп
walkdir = "2.5.0" #вложенные папки
anyhow = "1.0.100"
clap = "4.5.51"
docx-rs = "0.4.18"
serde_json = "1.0.145"
convert_case = "0.8.0"
stringzilla = "4.2.3"
time = "0.3.44"
chrono = "0.4.42"
unirust = "0.1.0"
#rzhavchina = { path = "./rzhavchina_proc_macro/" }
sysinfo = "0.37.2"
vergen = "9.0.6"
rayon = "1.11.0"
docx-rust = "0.1.10"
xml-rs = "1.0.0"
#quick-xml = "0.38.3"
pretty_assertions = "1.4.1"
console = "0.16.1"
rand = "0.10.0-rc.0"
#sha2 = "0.10.9"
#blake3 = "1.8.2"
serde = { version = "1.0.228", features = ["derive"] }
[workspace]
members = [
    "rzhavchina_proc_macro",
    #"examples"
]
# Явно указываем разрешение не-ASCII идентификаторов
[package.metadata]
non_ascii_idents = true

[profile.dev]
debug = true  # Включить отладочную информацию

[profile.release]
debug = true  # Также