[package]
name = "text_changer"
authors = ["AveN RU"]
version = "0.1.1"
description = "Заменитель слов по словарю"
edition = "2024"

[dependencies]
#для замера ОЗУ
cap = "*"
#смешные лица
indicatif = "*"
#постоянные данные
lazy_static = "*"
regex = "*"
calamine = "*"
rust_xlsxwriter = "*"
encoding_rs = "*"
encoding_rs_io = "*"
rtf-parser = "*"
zip = "*"
#foldhash = "*"
#доп
walkdir = "*" #вложенные папки
anyhow = "*"
clap = "*"
serde_json = "*"
convert_case = "*"
stringzilla = "*"
time = "*"
chrono = "*"
unirust = "*"
#rzhavchina = { path = "./rzhavchina_proc_macro/" }
sysinfo = "*"
vergen = "*"
rayon = "*"
xml-rs = "*"
#quick-xml = "*"
pretty_assertions = "*"
console = "*"
rand = "*"
dhat = "*"
#sha2 = "*"
#blake3 = "*"
rapidhash = "*"
serde = { version = "*", features = ["derive"] }
unicode-segmentation = "*"
tokio = { version = "*", features = ["full"]  }
tokio-macros = "*"
[workspace]
members = [
    "rzhavchina_proc_macro",
    #"examples"
]
# Явно указываем разрешение не-ASCII идентификаторов
[package.metadata]
non_ascii_idents = true

[profile.dev]
debug = true  # Включить отладочную информацию

[profile.release]
debug = true  # Также

[features]
dhat-heap = []    # if you are doing heap profiling
dhat-ad-hoc = []  # if you are doing ad hoc profiling

[rust]
debuginfo-level = 1
