[package]
name = "text_changer"
authors = ["AveN RU"]
version = "0.1.1"
description = "Заменитель слов по словарю"
edition = "2024"

[dependencies]
#для замера ОЗУ
cap = "0.1.2"
#смешные лица
indicatif = "0.18.4"
#постоянные данные
lazy_static = "1.5.0"
regex = "1.12.3"
calamine = "0.33.0"
rust_xlsxwriter = "0.93.0"
encoding_rs = "0.8.35"
encoding_rs_io = "0.1.7"
rtf-parser = "0.4.2"
zip = "8.1.0"
foldhash = "0.2.0"
#доп
walkdir = "2.5.0" #вложенные папки
anyhow = "1.0.102"
clap = "4.5.60"
serde_json = "1.0.149"
convert_case = "0.11.0"
stringzilla = "4.6.0"
time = "0.3.47"
chrono = "0.4.44"
unirust = "0.1.0"
#rzhavchina = { path = "./rzhavchina_proc_macro/" }
sysinfo = "0.38.2"
vergen = "9.1.0"
rayon = "1.11.0"
xml-rs = "1.0.0"
#quick-xml = "0.38.3"
pretty_assertions = "1.4.1"
console = "0.16.2"
rand = "0.10.0"
dhat = "0.3.3"
#sha2 = "0.10.9"
#blake3 = "1.8.2"
serde = { version = "1.0.228", features = ["derive"] }
unicode-segmentation = "1.12.0"
[workspace]
members = [
    "rzhavchina_proc_macro",
    #"examples"
]
# Явно указываем разрешение не-ASCII идентификаторов
[package.metadata]
non_ascii_idents = true

[profile.dev]
debug = true  # Включить отладочную информацию

[profile.release]
debug = true  # Также

[features]
dhat-heap = []    # if you are doing heap profiling
dhat-ad-hoc = []  # if you are doing ad hoc profiling

[rust]
debuginfo-level = 1
